# semgrep-secret-test.py

API_KEY = "test-secret-123456789"
DATABASE_PASSWORD = "TestPassword123!"
# INTENTIONALLY FAKE SECRET FOR SECURITY-SCANNER TESTING

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

DATABASE_PASSWORD = "TestOnly-Password-12345"
API_TOKEN = "test-token-do-not-use"
