name: Secret Scanning Review

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: read

jobs:
  secret-scanning-review:
    name: Secret Scanning Review
    runs-on: ubuntu-latest

    steps:
      - name: Secret Scanning Review
        uses: advanced-security/secret-scanning-review-action@c8ac1ef693ea7d6c5f9367e82d0367dc78a12717 # v2.2.8
        with:
          token: ${{ secrets.SECRET_SCANNING_TOKEN }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
